apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-ganesha
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ganesha
    spec:
      containers:
      - name: ganesha
        image: appscode/nfs-ganesha:2.3.0
        ports:
        - containerPort: 80