apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-ganesha-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    # FIXME: use the right IP
    server: 10.0.147.71
    path: "/"
