#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})
source /etc/envvars

glusterd --pid-file=/var/run/glusterd.pid

while true; do sleep 1; done
